stages:
  - package
  - build 
building package: 
    image: atlassian/maven:latest
    stage: package
    script: 
      - mvn package 
      - mkdir pkg
      - cp target/demo.war pkg/
    artifacts:
      paths: 
        - pkg
        - target
image building:
    image: docker:latest 
    stage: build
    services:
       - name: docker:dind
         alias: docker
    variables:
        DOCKER_HOST: tcp://docker:2375/
        DOCKER_DRIVER: overlay2
        DOCKER_TLS_CERTDIR: "" 
    before_script:
       -  docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    script:
      - docker build -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG" .
      - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"