stages:
  - package
building image: 
    image: maven:latest
    stage: package
    tags:
      - Test # this is the tag for the instance we connected.
    script: 
      - mvn package 
      - mkdir pkg
      - cp target/demo.war pkg/
    artifacts:
      paths: 
        - pkg
        - target
